import json

nb_ch7 = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {"language_info": {"name": "python"}},
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# **Chapter 7: Communication Protocols & Data Formats**\n\n",
    "In a distributed system, every request crosses a network boundary. The choice of *how* services talk to each other — and *what shape* that data takes — affects latency, developer experience, coupling, and scalability. This chapter covers the protocols and serialization formats that underpin modern distributed architectures.\n\n",
    "---\n\n",
    "## **7.1 Synchronous vs. Asynchronous Communication**\n\n",
    "Before choosing a specific protocol, decide whether the caller *waits* for a response or *fires and forgets*.\n\n",
    "| Style | Caller blocks? | Use when |\n",
    "|-------|---------------|----------|\n",
    "| Synchronous (HTTP, gRPC) | Yes | You need an immediate answer (user login, read API) |\n",
    "| Asynchronous (queues, events) | No | Work can happen later (email, analytics, order fulfillment) |\n\n",
    "**Key trade-off**: Synchronous calls are simpler to reason about but create temporal coupling — if the downstream service is slow or down, the caller is blocked or fails.\n\n",
    "---\n\n",
    "## **7.2 REST (Representational State Transfer)**\n\n",
    "**REST** is an architectural style — not a protocol — built on top of HTTP. It is the dominant style for public-facing APIs because HTTP is universally supported and REST is human-readable.\n\n",
    "### **Core Constraints**\n\n",
    "1. **Stateless**: Each request carries all the information the server needs. The server holds no session state between requests.\n",
    "2. **Uniform interface**: Resources are identified by URLs; actions are expressed via HTTP verbs.\n",
    "3. **Client-server separation**: The UI and storage concerns are separated.\n",
    "4. **Cacheable**: Responses explicitly declare whether they can be cached.\n\n",
    "### **HTTP Verbs and their Semantics**\n\n",
    "| Verb | Meaning | Idempotent? | Safe? |\n",
    "|------|---------|-------------|-------|\n",
    "| GET | Read a resource | Yes | Yes |\n",
    "| POST | Create / trigger action | No | No |\n",
    "| PUT | Replace entire resource | Yes | No |\n",
    "| PATCH | Partial update | No | No |\n",
    "| DELETE | Remove resource | Yes | No |\n\n",
    "**Idempotent** means calling the same request multiple times produces the same result. This matters for retry logic — safe to retry a `PUT` after a timeout, dangerous to retry a `POST` (might create duplicates).\n\n",
    "### **REST Request/Response Flow**\n\n",
    "```text\n",
    "Client                         Server\n",
    "  │                              │\n",
    "  │  GET /users/42               │\n",
    "  │  Accept: application/json    │\n",
    "  │  Authorization: Bearer <tok> │\n",
    "  │─────────────────────────────▶│\n",
    "  │                              │  Look up user 42\n",
    "  │                              │  in database\n",
    "  │  200 OK                      │\n",
    "  │  Content-Type: application/json\n",
    "  │  {\"id\":42,\"name\":\"Alice\"}    │\n",
    "  │◀─────────────────────────────│\n",
    "```\n\n",
    "### **REST Best Practices**\n\n",
    "- Use nouns for resources, not verbs: `/orders` not `/getOrders`\n",
    "- Use plural resource names: `/users/42` not `/user/42`\n",
    "- Return meaningful HTTP status codes: `200 OK`, `201 Created`, `400 Bad Request`, `404 Not Found`, `429 Too Many Requests`, `500 Internal Server Error`\n",
    "- Version your API: `/v1/users` so you can evolve without breaking clients\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "# Python example: building a simple REST API with Flask\n",
    "# (Illustrative — shows REST patterns, not a runnable server here)\n\n",
    "from flask import Flask, request, jsonify, abort\n\n",
    "app = Flask(__name__)\n\n",
    "# In-memory store (replace with a real database)\n",
    "users = {1: {'id': 1, 'name': 'Alice', 'email': 'alice@example.com'}}\n\n",
    "@app.route('/v1/users/<int:user_id>', methods=['GET'])\n",
    "def get_user(user_id):\n",
    "    \"\"\"GET /v1/users/42 -> return user or 404\"\"\"\n",
    "    user = users.get(user_id)\n",
    "    if not user:\n",
    "        abort(404, description=f'User {user_id} not found')\n",
    "    return jsonify(user), 200\n\n",
    "@app.route('/v1/users', methods=['POST'])\n",
    "def create_user():\n",
    "    \"\"\"POST /v1/users -> create and return 201 Created\"\"\"\n",
    "    data = request.get_json()\n",
    "    if not data or 'name' not in data:\n",
    "        abort(400, description='name is required')\n",
    "    new_id = max(users.keys()) + 1\n",
    "    users[new_id] = {'id': new_id, **data}\n",
    "    return jsonify(users[new_id]), 201\n\n",
    "@app.route('/v1/users/<int:user_id>', methods=['DELETE'])\n",
    "def delete_user(user_id):\n",
    "    \"\"\"DELETE /v1/users/42 -> idempotent: 204 whether found or not\"\"\"\n",
    "    users.pop(user_id, None)\n",
    "    return '', 204\n"
   ],
   "outputs": [],
   "execution_count": null
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n\n",
    "## **7.3 GraphQL**\n\n",
    "**GraphQL** is a query language for APIs developed by Facebook (Meta) in 2012. Instead of many REST endpoints each returning a fixed shape, GraphQL exposes a *single endpoint* where clients specify exactly the data they need.\n\n",
    "### **The Problem GraphQL Solves**\n\n",
    "With REST, you often face:\n",
    "- **Over-fetching**: The endpoint returns 30 fields but you only need 3.\n",
    "- **Under-fetching**: One endpoint doesn't return enough data, so you make 3 more requests (the N+1 problem).\n\n",
    "**GraphQL solution**: The client declares its data requirements in the query. The server returns exactly that shape — no more, no less.\n\n",
    "```text\n",
    "REST: Multiple round-trips for a profile page\n",
    "──────────────────────────────────────────────\n",
    "GET /users/42            → user name, email\n",
    "GET /users/42/posts      → post IDs + titles\n",
    "GET /posts/7/comments    → comment count\n",
    "3 requests, 3 round trips\n",
    "\n",
    "GraphQL: One query, one response\n",
    "──────────────────────────────────────────────\n",
    "POST /graphql\n",
    "{\n",
    "  user(id: 42) {\n",
    "    name\n",
    "    email\n",
    "    posts(last: 5) {\n",
    "      title\n",
    "      commentCount\n",
    "    }\n",
    "  }\n",
    "}\n",
    "→ Exactly the fields requested, in one round trip\n",
    "```\n\n",
    "### **When to Use GraphQL**\n\n",
    "✅ Mobile apps (minimize bandwidth with precise queries)  \n",
    "✅ Frontend teams move fast without waiting for new API endpoints  \n",
    "✅ Aggregating data from multiple services in a single call  \n",
    "❌ Simple CRUD APIs where REST is perfectly adequate  \n",
    "❌ Real-time streaming (GraphQL Subscriptions add complexity)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n\n",
    "## **7.4 gRPC (Google Remote Procedure Call)**\n\n",
    "**gRPC** is a high-performance RPC framework from Google. It uses **Protocol Buffers** (protobuf) for serialization and **HTTP/2** as the transport layer.\n\n",
    "### **How gRPC Differs from REST**\n\n",
    "| Aspect | REST/JSON | gRPC/Protobuf |\n",
    "|--------|-----------|---------------|\n",
    "| Protocol | HTTP/1.1 | HTTP/2 |\n",
    "| Payload | Text (JSON) | Binary (protobuf) |\n",
    "| Schema | Optional (OpenAPI) | Required (.proto file) |\n",
    "| Speed | Moderate | ~5–10× faster serialization |\n",
    "| Streaming | No (HTTP/1.1) | Bidirectional streaming |\n",
    "| Browser support | Universal | Limited (needs grpc-web) |\n\n",
    "### **gRPC Service Definition (`.proto` file)**\n\n",
    "A `.proto` file acts as a contract between client and server. gRPC generates client and server code in your target language from this schema.\n\n",
    "```text\n",
    "// user.proto\n",
    "syntax = \"proto3\";\n",
    "\n",
    "service UserService {\n",
    "  rpc GetUser (GetUserRequest) returns (User);\n",
    "  rpc ListUsers (ListUsersRequest) returns (stream User); // Server streaming\n",
    "}\n",
    "\n",
    "message GetUserRequest {\n",
    "  int64 id = 1;\n",
    "}\n",
    "\n",
    "message User {\n",
    "  int64  id    = 1;\n",
    "  string name  = 2;\n",
    "  string email = 3;\n",
    "}\n",
    "```\n\n",
    "### **gRPC Communication Patterns**\n\n",
    "```text\n",
    "┌────────────────────────────────────────────────────────────────┐\n",
    "│                   gRPC Communication Patterns                  │\n",
    "├────────────────────────────────────────────────────────────────┤\n",
    "│                                                                │\n",
    "│  1. Unary RPC (like REST)                                      │\n",
    "│     Client ──── Request ────▶ Server                          │\n",
    "│     Client ◀─── Response ─── Server                          │\n",
    "│                                                                │\n",
    "│  2. Server Streaming (e.g., live updates)                      │\n",
    "│     Client ──── Request ────▶ Server                          │\n",
    "│     Client ◀─── Response 1 ── Server                         │\n",
    "│     Client ◀─── Response 2 ── Server                         │\n",
    "│     Client ◀─── Response N ── Server                         │\n",
    "│                                                                │\n",
    "│  3. Client Streaming (e.g., uploading log chunks)              │\n",
    "│     Client ──── Request 1 ──▶ Server                          │\n",
    "│     Client ──── Request N ──▶ Server                          │\n",
    "│     Client ◀─── Response ─── Server                          │\n",
    "│                                                                │\n",
    "│  4. Bidirectional Streaming (e.g., chat, real-time telemetry)  │\n",
    "│     Client ◀──────────────── Server  (simultaneous streams)   │\n",
    "│                                                                │\n",
    "└────────────────────────────────────────────────────────────────┘\n",
    "```\n\n",
    "The diagram above shows the four gRPC call types. Bidirectional streaming is particularly powerful for real-time use cases like live dashboards or game servers.\n\n",
    "### **When to Use gRPC**\n\n",
    "✅ Internal service-to-service communication where speed matters  \n",
    "✅ Polyglot environments (protobuf generates client code in 10+ languages)  \n",
    "✅ Low-latency, high-throughput microservice communication  \n",
    "❌ Public APIs consumed by browsers (gRPC-Web adds overhead)  \n",
    "❌ Teams unfamiliar with protobuf schema management\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n\n",
    "## **7.5 WebSockets and Server-Sent Events (SSE)**\n\n",
    "HTTP is fundamentally request-response: the client initiates, the server responds. For real-time applications — live scores, collaborative editing, notifications — you need the server to *push* data to the client without the client polling.\n\n",
    "### **WebSockets**\n\n",
    "A **WebSocket** establishes a persistent, full-duplex (bidirectional) TCP connection over HTTP. After the initial HTTP upgrade handshake, both parties can send frames at any time.\n\n",
    "```text\n",
    "WebSocket Connection Lifecycle:\n",
    "\n",
    "Client                                    Server\n",
    "  │                                          │\n",
    "  │  GET /ws  HTTP/1.1                       │\n",
    "  │  Upgrade: websocket                      │\n",
    "  │  Connection: Upgrade                     │\n",
    "  │─────────────────────────────────────────▶│\n",
    "  │                                          │\n",
    "  │  101 Switching Protocols                 │\n",
    "  │  Upgrade: websocket                      │\n",
    "  │◀─────────────────────────────────────────│\n",
    "  │                                          │\n",
    "  │  [Persistent TCP connection open]        │\n",
    "  │                                          │\n",
    "  │  {\"type\": \"chat\", \"msg\": \"Hello\"}        │\n",
    "  │─────────────────────────────────────────▶│\n",
    "  │                                          │\n",
    "  │          {\"type\": \"message\", \"from\": \"Bob\"}\n",
    "  │◀─────────────────────────────────────────│\n",
    "  │         (server pushes without request)  │\n",
    "```\n\n",
    "**When to use WebSockets**: Chat applications, live collaboration (Google Docs), multiplayer games, real-time trading dashboards.\n\n",
    "### **Server-Sent Events (SSE)**\n\n",
    "**SSE** is a simpler alternative where the server can push events over a regular HTTP connection, but only in one direction (server → client). The client subscribes with a regular `GET` request and keeps the connection open.\n\n",
    "| | WebSocket | SSE |\n",
    "|-|-----------|-----|\n",
    "| Direction | Bidirectional | Server → Client only |\n",
    "| Protocol | Upgraded TCP | Plain HTTP |\n",
    "| Browser support | Universal | Universal (except IE) |\n",
    "| Reconnection | Manual | Automatic |\n",
    "| Use case | Chat, games | Notifications, live feeds |\n\n",
    "**Rule of thumb**: Use SSE for simple one-way push (news feeds, build logs, progress bars). Use WebSockets when the client also needs to send real-time data back.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n\n",
    "## **7.6 Data Serialization Formats**\n\n",
    "The *format* of the data being transmitted affects payload size, serialization speed, schema enforcement, and human-readability.\n\n",
    "### **JSON (JavaScript Object Notation)**\n\n",
    "**JSON** is the default for REST APIs. It is human-readable, universally supported, and flexible.\n\n",
    "- ✅ Human-readable and debuggable\n",
    "- ✅ Supported in every language natively\n",
    "- ❌ Verbose — field names repeated in every record\n",
    "- ❌ No binary support (base64 encoding needed)\n",
    "- ❌ No schema enforcement by default\n\n",
    "### **Protocol Buffers (protobuf)**\n\n",
    "**Protocol Buffers** are Google's language-neutral, binary serialization format. They require a `.proto` schema file but produce payloads 3–10× smaller than JSON and serialize/deserialize 5–10× faster.\n\n",
    "```text\n",
    "Same data: JSON vs protobuf wire size comparison\n",
    "\n",
    "JSON representation (82 bytes):\n",
    "  {\"id\": 42, \"name\": \"Alice\", \"email\": \"alice@example.com\"}\n",
    "\n",
    "Protobuf binary (28 bytes):\n",
    "  \\x08\\x2a\\x12\\x05Alice\\x1a\\x11alice@example.com\n",
    "  └── not human-readable, but ~65% smaller\n",
    "\n",
    "At 1 billion requests/day:\n",
    "  JSON:    82 GB of payload data/day\n",
    "  Protobuf: 28 GB of payload data/day\n",
    "  Savings: 54 GB/day in bandwidth costs\n",
    "```\n\n",
    "The size difference compounds at scale — this is why Google, Netflix, and Uber use protobuf for internal services.\n\n",
    "### **MessagePack, Avro, Thrift**\n\n",
    "| Format | Schema? | Binary? | Best for |\n",
    "|--------|---------|---------|----------|\n",
    "| JSON | No | No | Public REST APIs, config files |\n",
    "| Protocol Buffers | Yes (.proto) | Yes | gRPC, high-throughput internal APIs |\n",
    "| MessagePack | No | Yes | Drop-in binary replacement for JSON |\n",
    "| Apache Avro | Yes (.avsc) | Yes | Kafka messages, data pipelines |\n",
    "| Thrift | Yes (.thrift) | Yes | Legacy Facebook services |\n",
    "| XML | No | No | SOAP services, document exchange |\n\n",
    "**Decision guide**: Start with JSON. Switch to protobuf or Avro when bandwidth or serialization latency becomes a bottleneck.\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "source": [
    "import json\n",
    "import struct\n",
    "import time\n\n",
    "# Demonstrate JSON vs manual binary serialization size difference\n\n",
    "# Sample user object\n",
    "user = {'id': 42, 'name': 'Alice', 'email': 'alice@example.com', 'age': 30}\n\n",
    "# JSON serialization\n",
    "json_bytes = json.dumps(user).encode('utf-8')\n",
    "print(f'JSON payload:    {json_bytes}')\n",
    "print(f'JSON size:       {len(json_bytes)} bytes')\n",
    "print()\n\n",
    "# Measure serialization speed\n",
    "iterations = 100_000\n\n",
    "start = time.perf_counter()\n",
    "for _ in range(iterations):\n",
    "    json.dumps(user)\n",
    "json_time = time.perf_counter() - start\n\n",
    "start = time.perf_counter()\n",
    "for _ in range(iterations):\n",
    "    json.loads(json_bytes)\n",
    "json_parse_time = time.perf_counter() - start\n\n",
    "print(f'JSON serialize: {json_time*1000:.1f}ms for {iterations:,} iterations')\n",
    "print(f'JSON parse:     {json_parse_time*1000:.1f}ms for {iterations:,} iterations')\n",
    "print()\n",
    "print('For true protobuf comparison, install: pip install protobuf')\n",
    "print('Expected result: protobuf ~5x faster and ~60% smaller for structured data')\n"
   ],
   "outputs": [],
   "execution_count": null
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n\n",
    "## **7.7 API Design Patterns**\n\n",
    "### **Versioning Strategies**\n\n",
    "API versioning lets you evolve your API without breaking existing clients.\n\n",
    "| Strategy | Example | Pros | Cons |\n",
    "|----------|---------|------|------|\n",
    "| URL path | `/v2/users` | Obvious, cacheable | URLs change |\n",
    "| Header | `API-Version: 2` | Clean URLs | Less discoverable |\n",
    "| Query param | `/users?version=2` | Easy to test | Pollutes URLs |\n",
    "| Media type | `Accept: application/vnd.api.v2+json` | RESTful | Complex |\n\n",
    "**Recommendation**: Use URL path versioning (`/v1/`, `/v2/`). It is the most explicit and easiest to test in a browser or curl.\n\n",
    "### **Pagination Patterns**\n\n",
    "Never return unbounded collections. Three common strategies:\n\n",
    "```text\n",
    "1. Offset pagination (simple, but skips are possible on fast-changing data)\n",
    "   GET /users?offset=100&limit=20\n",
    "   → Returns records 101–120\n",
    "\n",
    "2. Cursor-based pagination (stable, efficient for large datasets)\n",
    "   GET /users?cursor=eyJpZCI6MTAwfQ==&limit=20\n",
    "   Response includes: { \"next_cursor\": \"eyJpZCI6MTIwfQ==\" }\n",
    "   → Stable across inserts/deletes; used by Twitter, Facebook\n",
    "\n",
    "3. Keyset pagination (fastest; requires sortable, unique key)\n",
    "   GET /users?after_id=100&limit=20\n",
    "   → Database: WHERE id > 100 LIMIT 20 (uses index efficiently)\n",
    "```\n\n",
    "### **Rate Limiting Headers**\n\n",
    "Always communicate rate limit status to API consumers:\n\n",
    "```text\n",
    "HTTP/1.1 200 OK\n",
    "X-RateLimit-Limit:     1000    # requests per hour\n",
    "X-RateLimit-Remaining:  423    # requests left in current window\n",
    "X-RateLimit-Reset:  1701388800  # Unix timestamp when window resets\n",
    "\n",
    "When exceeded:\n",
    "HTTP/1.1 429 Too Many Requests\n",
    "Retry-After: 3600\n",
    "```\n\n",
    "---\n\n",
    "## **7.8 Choosing the Right Protocol: Decision Guide**\n\n",
    "```text\n",
    "Start here: Who is the consumer?\n",
    "         │\n",
    "         ├─▶ External / browser / public API\n",
    "         │         │\n",
    "         │         ├─▶ Simple CRUD?           → REST/JSON\n",
    "         │         ├─▶ Complex queries?        → GraphQL\n",
    "         │         └─▶ Real-time push needed?  → WebSockets or SSE\n",
    "         │\n",
    "         └─▶ Internal service-to-service\n",
    "                   │\n",
    "                   ├─▶ Need maximum performance? → gRPC + protobuf\n",
    "                   ├─▶ Streaming data?            → gRPC streaming\n",
    "                   └─▶ Simple, team prefers REST?  → REST/JSON (fine!)\n",
    "```\n\n",
    "There is no universally \"best\" choice. REST dominates public APIs for good reason: simplicity and ubiquity. gRPC wins for internal microservice meshes at scale. GraphQL shines for product APIs serving multiple frontends.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div style='width:100%; display:flex; justify-content:space-between; align-items:center; margin: 1em 0;'>\n",
    "  <a href='../2. The_building_blocks/6. load_balancing_and_traffic_management.ipynb' style='font-weight:bold; font-size:1.05em;'>&larr; Previous</a>\n",
    "  <a href='../TOC.md' style='font-weight:bold; font-size:1.05em; text-align:center;'>Table of Contents</a>\n",
    "  <a href='8. distributed_data_management.ipynb' style='font-weight:bold; font-size:1.05em;'>Next &rarr;</a>\n",
    "</div>\n"
   ]
  }
 ]
}

path = '/media/ankit/Programming/Projects/Dev-Handbook/system_design/3. Distributes_systems_fundamentals/7. communication_protocols_and_data_formats.ipynb'
with open(path, 'w') as f:
    json.dump(nb_ch7, f, ensure_ascii=False, indent=1)
print("Chapter 7 written.")
